n = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(n))
print('É alfanúmérico?', n.isalnum())
print('É decimal?', n.isdecimal())
print('Inicia com maiúscula?', n.istitle())
print('É um número?', n.isnumeric())
print('Só tem espaços?', n.isspace())
print('Escrito com maiúsculas?', n.isupper())
print('Escrito com minúsculas?', n.islower())